2025-04-30 13:36:25 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 13:40:00 [[31merror[39m]: TypeError: Cannot read properties of undefined (reading 'error')
    at Job.job (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\services\cartReminder.js:301:16)
2025-04-30 13:45:03 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 13:45:28 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 13:49:04 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 14:04:27 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 14:06:10 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 14:12:20 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 14:19:43 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 14:21:50 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 14:22:59 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 14:45:19 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 14:49:53 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 15:10:35 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 15:16:15 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 15:16:19 [[31merror[39m]: TypeError: logger.info is not a function
    at Server.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:218:10)
    at Object.onceWrapper (node:events:632:28)
    at Server.emit (node:events:530:35)
    at emitListeningNT (node:net:1980:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:89:21)
2025-04-30 15:16:26 [[31merror[39m]: TypeError: logger.info is not a function
    at Server.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:218:10)
    at Object.onceWrapper (node:events:632:28)
    at Server.emit (node:events:530:35)
    at emitListeningNT (node:net:1980:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:89:21)
2025-04-30 15:17:30 [[31merror[39m]: TypeError: logger.info is not a function
    at Server.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:218:10)
    at Object.onceWrapper (node:events:632:28)
    at Server.emit (node:events:530:35)
    at emitListeningNT (node:net:1980:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:89:21)
2025-04-30 15:22:59 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 15:25:30 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 15:34:02 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 15:44:53 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 15:55:13 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 15:59:39 [[31merror[39m]: TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\router\index.js:469:13)
    at Function.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:283:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
2025-04-30 16:00:04 [[31merror[39m]: TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\router\index.js:469:13)
    at Function.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:283:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
2025-04-30 16:01:46 [[31merror[39m]: TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\router\index.js:469:13)
    at Function.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:283:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
2025-04-30 16:03:00 [[31merror[39m]: ReferenceError: authMiddleware is not defined
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\middleware\authMiddleware.js:72:18)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\routes\reviewRoutes.js:6:14)
2025-04-30 16:03:41 [[31merror[39m]: TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\router\index.js:469:13)
    at Function.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:283:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
2025-04-30 16:05:09 [[31merror[39m]: TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\router\index.js:469:13)
    at Function.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:283:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
2025-04-30 16:06:50 [[31merror[39m]: TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\router\index.js:469:13)
    at Function.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:283:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
2025-04-30 16:08:07 [[31merror[39m]: TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\router\index.js:469:13)
    at Function.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:283:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
2025-04-30 16:09:24 [[31merror[39m]: TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\router\index.js:469:13)
    at Function.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:283:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
2025-04-30 16:12:18 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 16:35:01 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 16:35:09 [[31merror[39m]: TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\router\index.js:469:13)
    at Function.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:183:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
2025-04-30 16:35:16 [[31merror[39m]: TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\router\index.js:469:13)
    at Function.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:183:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
2025-04-30 16:36:30 [[31merror[39m]: TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\router\index.js:469:13)
    at Function.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:283:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
2025-04-30 16:37:06 [[31merror[39m]: TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\router\index.js:469:13)
    at Function.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:183:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
2025-04-30 16:38:01 [[31merror[39m]: TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\router\index.js:469:13)
    at Function.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:183:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
2025-04-30 16:50:17 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 17:00:53 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 17:04:13 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 17:08:34 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 17:21:09 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 17:54:36 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 17:55:44 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 18:15:29 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 18:19:10 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-04-30 18:21:47 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-05-01 10:51:31 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-05-01 11:16:32 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-05-01 11:28:57 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-05-01 11:42:08 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-05-01 11:53:06 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-05-01 12:01:59 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-05-01 12:42:30 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-05-01 13:10:37 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-05-01 13:16:22 [[31merror[39m]: OverwriteModelError: Cannot overwrite `Cart` model once compiled.
    at Mongoose.model (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\mongoose.js:610:13)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\models\Cart.js:109:27)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-05-01 13:19:00 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-05-01 13:24:37 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-05-01 13:24:40 [[31merror[39m]: OverwriteModelError: Cannot overwrite `Cart` model once compiled.
    at Mongoose.model (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\mongoose.js:610:13)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\models\Cart.js:109:27)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-05-01 15:43:25 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-05-01 15:45:58 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-05-01 15:46:41 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-05-01 15:47:09 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-05-01 15:51:15 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-05-01 15:53:12 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-05-02 10:43:16 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-05-02 10:45:17 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:225:23)
    at process.emit (node:events:518:28)
2025-05-02 10:52:32 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:227:23)
    at process.emit (node:events:518:28)
2025-05-02 11:01:25 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 11:12:31 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 11:20:41 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 11:29:15 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 12:34:51 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 12:37:56 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 12:38:53 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 12:42:52 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 12:50:58 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 12:57:08 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 13:08:50 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 13:51:09 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 13:53:13 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 14:06:40 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 14:28:25 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 14:43:27 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 14:47:36 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 15:04:58 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 15:08:51 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 15:25:59 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 15:35:11 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 15:48:07 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 16:00:16 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 16:14:10 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 16:23:00 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 16:34:33 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 16:49:15 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 17:11:43 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 17:25:28 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 17:37:59 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 17:41:02 [[31merror[39m]: AxiosError: Request failed with status code 401
    at settle (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\axios\dist\node\axios.cjs:2049:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\axios\dist\node\axios.cjs:3166:11)
    at IncomingMessage.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
    at Axios.request (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\axios\dist\node\axios.cjs:4276:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Timeout._onTimeout (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\routes\orders.js:4505:5)
2025-05-02 17:46:08 [[31merror[39m]: AxiosError: Request failed with status code 401
    at settle (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\axios\dist\node\axios.cjs:2049:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\axios\dist\node\axios.cjs:3166:11)
    at IncomingMessage.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
    at Axios.request (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\axios\dist\node\axios.cjs:4276:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Timeout._onTimeout (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\routes\orders.js:4505:5)
2025-05-02 17:54:16 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 17:56:23 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 17:59:17 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 18:04:21 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 18:24:21 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 18:28:18 [[31merror[39m]: ReferenceError: authMiddleware is not defined
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\routes\delivered.js:8:34)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:259:25)
2025-05-02 18:35:59 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-02 18:38:29 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-03 10:48:56 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-03 10:56:50 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-03 11:31:28 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-03 11:31:37 [[31merror[39m]: Error: Cannot find module './deliveredStatus'
Require stack:
- C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\jobs\cron.js
- C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function._load (node:internal/modules/cjs/loader:1055:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\jobs\cron.js:5:31)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
2025-05-03 11:33:14 [[31merror[39m]: Error: Cannot find module './deliveredStatus'
Require stack:
- C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\jobs\cron.js
- C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function._load (node:internal/modules/cjs/loader:1055:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\jobs\cron.js:5:31)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
2025-05-03 11:33:23 [[31merror[39m]: Error: Cannot find module './deliveredStatus'
Require stack:
- C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\jobs\cron.js
- C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function._load (node:internal/modules/cjs/loader:1055:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\jobs\cron.js:5:31)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
2025-05-03 11:36:45 [[31merror[39m]: Error: Cannot find module './deliveredStatus'
Require stack:
- C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\jobs\cron.js
- C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function._load (node:internal/modules/cjs/loader:1055:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\jobs\cron.js:5:31)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
2025-05-03 11:39:13 [[31merror[39m]: Error: Cannot find module './deliveredStatus'
Require stack:
- C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\jobs\cron.js
- C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function._load (node:internal/modules/cjs/loader:1055:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\jobs\cron.js:5:31)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
2025-05-03 11:40:03 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:458:23)
    at process.emit (node:events:518:28)
2025-05-03 11:40:06 [[31merror[39m]: Error: Cannot find module './deliveredStatus'
Require stack:
- C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\jobs\cron.js
- C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function._load (node:internal/modules/cjs/loader:1055:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\jobs\cron.js:5:31)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
2025-05-03 11:41:55 [[31merror[39m]: Error: Cannot find module './deliveredStatus'
Require stack:
- C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\jobs\cron.js
- C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function._load (node:internal/modules/cjs/loader:1055:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\jobs\cron.js:5:31)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
2025-05-03 11:49:35 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:458:23)
    at process.emit (node:events:518:28)
2025-05-03 12:00:18 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:458:23)
    at process.emit (node:events:518:28)
2025-05-03 12:01:08 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\jobs\cron.js:242:23)
    at process.emit (node:events:530:35)
2025-05-03 12:39:43 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\jobs\cron.js:242:23)
    at process.emit (node:events:530:35)
2025-05-03 12:45:25 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-03 13:05:24 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-03 14:42:28 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-03 14:54:05 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-03 14:55:46 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-03 16:21:59 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-03 16:30:47 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-06 10:45:54 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-06 11:08:51 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-06 11:12:20 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-06 11:27:08 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-06 11:33:35 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-06 12:07:06 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-06 14:16:26 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-06 14:59:28 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-06 15:14:02 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-06 16:35:00 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-07 10:37:49 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-07 11:08:47 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-07 11:14:35 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-07 12:15:14 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-07 14:30:19 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-07 14:30:25 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-07 14:50:20 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-07 14:54:02 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-07 15:27:33 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-07 15:41:03 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-07 15:47:03 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-07 15:57:35 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-07 17:20:04 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-07 17:56:42 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-07 18:03:39 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-07 18:14:34 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-07 18:31:04 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-07 18:35:43 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-07 18:36:44 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-08 10:39:31 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-08 10:44:02 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-08 12:01:06 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-08 13:05:51 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-08 14:10:25 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-08 14:15:53 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-08 14:21:10 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-08 14:22:27 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-08 14:22:53 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-08 15:03:43 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-08 15:16:21 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-08 15:45:36 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-10 10:57:42 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-13 15:22:15 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-05-14 10:52:56 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-06-17 11:18:57 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-06-17 11:20:53 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-06-17 11:38:37 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
2025-07-14 19:51:07 [[31merror[39m]: MongooseError: Connection.prototype.close() no longer accepts a callback
    at NativeConnection.close (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\node_modules\mongoose\lib\connection.js:1205:11)
    at process.<anonymous> (C:\Users\Ajay Panjala\Desktop\E-commerce-3\Backend\server.js:342:23)
    at process.emit (node:events:518:28)
